language: rust

GH_TOKEN: &GH_TOKEN
  secure: "BfXtnEr/vcMoaybUqSNDoSkD7lpSTteWEC8+lUIRKJXlJjzD9Urk3EJMmtAGLJZV7gG3dZCe6vD2/PQ4BadyEN4Qg+sm8CT/5Zmy5otoat8U4gtSHreY52Qn0oPM24Sa/hXYHCmQSmrFkfDO5bc9SaUBMf0ZUBP1cazZWDIywxF5KsyhCWL1QDebjtar+hvdVI1yNTiSBuCjBSJe2m87/DczZJI7kxofiqgh95Pk5erO35DAsVXtEc4CVUfwnkRQB0Q2xRGQQ0phR/EEy5K6IITahYkCPXmp02AxbXaSOrNh6Qxcl082KDI7IVS16sq5cSyP6opmmqnqKjkeQuN+9Xu+wW+TWRGAn9sRn8dbAqHmh7/5KKIdjDNZzb2YnrZtw8nks9xPNIjEIqV+0S3KHL7+bObJ2T8aBv/oyegmU+qfopgGjQg6svtOlMO2nfaVJrTxA2653+IVuOfctdXRKEgBtXhuvKr/K2fr9mBeW8Dz+ejZd3DsDiVE99CalqPeOCPiimnGAKRjBnEysF3e84CNRQSX0m1Barhrr4S8U2S4BtCzZlAX7XXibfQQOc9h1HAP/LwjcMTc1MS2Mk1UykeoUVjmC5UCF1EYZ85KveTmM4aAb/oT9Zp87zibxXZXVlYaHDwUaABdEMuVxfA2VnX8gm9R4q+d9nNbB63SiXs="

CARGO_TOKEN: &CARGO_TOKEN
  secure: "qIxvuVsmkbox2V+IFVo91qaOg+dOi7Q0KwwLklj8O5A3B7SJc+ETGZ5m93q7qFHt1z7QuW6GkdcAeQj1UGJZtNO35k9Q9EQZwJYWTzOISKXaVP4Df3iechcG19NQHaeJQIKk2iB+QvHyvKsXcRVZiHoGlv+J8GcKpER9tJ2S7Y3+o7XimwS0dORgNTVe7RWvpx5m3sGgNs4HXnlwf6fMFL+t6MwMadTteyYGkgtQ0P3xNDRS5TihUphidTlaOPmAx1nrzwjdvBFrtddgaVVYQ+JplJ+g8TNo8CTgDEtlsjoM4YB+YoOm4UfWn/hGl/Ca9yguCXQL/Mq9kkm2dbD+8tOs3oPGISHhU2oltJmqL8EB5lN4P/BsP9f5DbGq9QB/CwtGC1jLqMZTPFiL9xWC9OuEnC34LH++Xgwd8a+I6OpvP4g7w62IMiZZaNULwE7stwDThX+HQdfj/Qhp3HtQ5C/dStnjMPTE1PxzNZehxjj3CiPD84rABfsOvi/09ZAgyWD6jeeWDy9v4vci0fSC9+qazBKGws4LVqJMeaA6vxTpnO77iS65RNjZNHZ9G9FuHCWoo1R7ws/MoAzcXBT9N0wHXbsj5HK0E+JUYra579AHTifngfKdwM5Lz7CMgtUhGJBZdMvfGYwR4mtAocmsnUy7yF2xxiGC9+ZAhHjMDew="

DEPLOY_TO_GITHUB: &DEPLOY_TO_GITHUB
  before_deploy:
  - git config --local user.name "Will Daly"
  - git config --local user.email "will.e.daly@gmail.com"
  - name="devlog-$TRAVIS_TAG-$TARGET"
  - mkdir $name
  - cp target/$TARGET/release/devlog $name/
  - cp README.md LICENSE $name/
  - tar czvf $name.tar.gz $name
  deploy:
    provider: releases
    api_key: *GH_TOKEN
    file: devlog-$TRAVIS_TAG-$TARGET.tar.gz
    skip_cleanup: true
    name: $TRAVIS_TAG
    on:
      branch: master
      tags: true

env:
    global:
        - TMPDIR=$TRAVIS_BUILD_DIR

matrix:
  include:

  - name: Tests
    rust: stable
    script:
    - cargo test
    - rustup component add rustfmt-preview
    - cargo fmt --version
    - cargo fmt --all -- --check

  - name: Cargo Package
    deploy:
      provider: cargo
      token: *CARGO_TOKEN
      on:
        branch: master
        tags: true

  - name: Linux Binary
    rust: stable
    env: TARGET=x86_64-unknown-linux-musl
    before_script: rustup target add $TARGET
    script: cargo build --release --target $TARGET
    addons:
      apt:
        packages:
        - musl-tools
    <<: *DEPLOY_TO_GITHUB

  - name: macOS Binary
    rust: stable
    env: MACOSX_DEPLOYMENT_TARGET=10.7 TARGET=x86_64-apple-darwin
    os: osx
    script: cargo build --release --target $TARGET
    install: true
    <<: *DEPLOY_TO_GITHUB

  - name: Debian Package
    rust: stable
    before_script: cargo install cargo-deb
    addons:
      apt:
        packages:
        - dpkg
    script: cargo-deb --deb-version ${TRAVIS_TAG:-HEAD}
    deploy:
      provider: releases
      api_key: *GH_TOKEN
      file: target/debian/devlog_${TRAVIS_TAG}_amd64.deb
      skip_cleanup: true
      name: $TRAVIS_TAG
      on:
        branch: master
        tags: true

  - name: RPM Package
    rust: stable
    before_script:
        - cargo install cargo-rpm
        - sed -i "s/version = \"[^\"]*\"/version = \"${TRAVIS_TAG:-0.0.0}\"/" Cargo.toml
    addons:
      apt:
        packages:
        - rpm
    script: cargo build --release && cargo rpm build
    deploy:
      provider: releases
      api_key: *GH_TOKEN
      file: target/release/rpmbuild/RPMS/x86_64/devlog-${TRAVIS_TAG}-1.x86_64.rpm
      skip_cleanup: true
      name: $TRAVIS_TAG
      on:
        branch: master
        tags: true
