language: rust
os: linux

GH_TOKEN: &GH_TOKEN
  secure: "FblsFkvtWcVjRrWlTolENuV1PViNX9KYJ5LQ6L2mjrOGIIAznmynDUILxmTkqMaECk5Zb6zsT0hGvSXRkVGotRZBzTrq+ChA5lST3gJq2Mc9lkvjL6wiQYcngy7+sVM5MwpyZtU4Wg8Yvey0+92XncJkbfAChrEUbQA7TFgHf2Rh9Ihj54eQ7kGfSTwMiXeCcsvjcuE1+EFYLNZr/DpbczYyVh0Ha+AZDb7oNG5xtOqxYqKzRmREXjVntRgPLoqkslX4Oe9EL1z+JyXDAhtMET6u7gIjsf7ttj6n4LlY3RkeDqUSc1vX35//woCznpJ982QcmwSI8VOmWQ3Do5FotqIntZ99fGjOprg58K40LKk0ObOO25z63ReZn4IR+KfVrhQjBBLHw0L2tdAJMt1aZ6T10hfhDw2GMSGr4r121lXSPyr0keaGCS0hy2OyAXI9c0IX4zjVSGLFJg6BnRR15dIkH3R3JLghixhDxoN3MPcIxedNy4cnbSbRf6nbuzo2NU8Tb5/NBaO4SSn55sVi2/kb9+gA6uFoF8BxzX0pwTOeepWJoxJGzaG5c/R8cLzAqe+t7RpiSofaODazI9Bg8+up3JLhFPoYgaLsNKC8FQmpF8CAybbsXNpMv/Q1DBmn94Ulmr4t/CuPf9uo++QgpsCHX77cNiWbycgv+jtZ7PE="

CARGO_TOKEN: &CARGO_TOKEN
  secure: "SoYNVT8RMSc1x6OEU6dJE3pFvhbeHRpHuR3aP0L+Q6c1CeMmJ90DR6c8Ktxu4oOQCokXGOMMmCqkNTI4Td3Jl45Ituwiv2wS8hmwHNYh9JlJMisftPhTgQ3RlA1OPrTL/0emQsne60HElOEjnMJOKZEm0tvcEzTXopUOAhlt4/gauH2zH/kniwjvxzJrSuYJkd6eBQwcWaHX0SxPgW/T/6fQm+T2WgNhV2SZFVizeKzEuqKC+vH+Kq1trOhj/+jQQaNiSkgJmdfMrV/AuG6lvb29rNNVtjt+uoVCQImXv93q8FwtU9S8GpQ8LViuWCw7v+plhmDE0KSbqfVDd9cO2/FjmuQ/bks6zz55Hwhx/QIm7JpPrONjiJLWOoaEogX28rvCFki3KIiVpA95xY5OqQ90mFb4ZqveiKVpYJjRtp6Fj1AxV4G+7BXykAKurDxKxvt3zCFcs0aRZsrNe8OVMcyKCG+9+vURwRaLCH1gg8j6XUBlQCyPtlF+2D/Y8NzhdSEidBOiuia0r2QZoQeKp5nnd3lsN4mLCKPLzNn+LCdIyyCYJ8fF0NhJbPraF+rgu7xF80J+yHRarepB26irLxP7Mui0OO4KxSD+aRssRlmFfUmvtt0Pm0DgB4EfJ2UfdVc9jTRS5SbBUF70b2ESuO8N7PPZAUWJoOlnlIojDhE="

DEPLOY_TO_GITHUB: &DEPLOY_TO_GITHUB
  before_deploy:
  - git config --local user.name "Will Daly"
  - git config --local user.email "will.e.daly@gmail.com"
  - name="devlog-$TRAVIS_TAG-$TARGET"
  - mkdir $name
  - cp target/$TARGET/release/devlog $name/
  - cp README.md LICENSE $name/
  - tar czvf $name.tar.gz $name
  deploy:
    provider: releases
    token: *GH_TOKEN
    file: devlog-$TRAVIS_TAG-$TARGET.tar.gz
    skip_cleanup: true
    name: $TRAVIS_TAG
    on:
      branch: master
      tags: true

env:
    global:
        - TMPDIR=$TRAVIS_BUILD_DIR

jobs:
  include:

  - name: Tests
    rust: stable
    script:
    - cargo test
    - rustup component add rustfmt-preview
    - cargo fmt --version
    - cargo fmt --all -- --check

  - name: Cargo Package
    deploy:
      provider: cargo
      token: *CARGO_TOKEN
      on:
        branch: master
        tags: true

  - name: Linux Binary
    rust: stable
    env: TARGET=x86_64-unknown-linux-musl
    before_script: rustup target add $TARGET
    script: cargo build --release --target $TARGET
    addons:
      apt:
        packages:
        - musl-tools
    <<: *DEPLOY_TO_GITHUB

  - name: macOS Binary
    rust: stable
    env: MACOSX_DEPLOYMENT_TARGET=10.7 TARGET=x86_64-apple-darwin
    os: osx
    script: cargo build --release --target $TARGET
    install: true
    <<: *DEPLOY_TO_GITHUB

  - name: Debian Package
    rust: stable
    before_script: cargo install cargo-deb
    addons:
      apt:
        packages:
        - dpkg
    script: cargo-deb --deb-version ${TRAVIS_TAG:-HEAD}
    deploy:
      provider: releases
      token: *GH_TOKEN
      file: target/debian/devlog_${TRAVIS_TAG}_amd64.deb
      skip_cleanup: true
      name: $TRAVIS_TAG
      on:
        branch: master
        tags: true

  - name: RPM Package
    rust: stable
    before_script:
        - cargo install cargo-rpm
        - sed -i "s/version = \"[^\"]*\"/version = \"${TRAVIS_TAG:-0.0.0}\"/" Cargo.toml
    addons:
      apt:
        packages:
        - rpm
    script: cargo build --release && cargo rpm build
    deploy:
      provider: releases
      token: *GH_TOKEN
      file: target/release/rpmbuild/RPMS/x86_64/devlog-${TRAVIS_TAG}-1.x86_64.rpm
      skip_cleanup: true
      name: $TRAVIS_TAG
      on:
        branch: master
        tags: true
