[package]
name = "devlog"
version = "0.1.0"
authors = ["Will Daly"]
edition = "2018"
description = "devlog is a command-line tool for tracking daily development tasks."
repository = "https://github.com/wedaly/devlog"
homepage = "https://devlog-cli.org"
readme = "README.md"
keywords = ["task", "todo", "development", "planning", "cli"]
categories = ["command-line-utilities", "text-processing"]
license = "MIT License"

[dependencies]
chrono = "0.4.6"
clap = "2.33.0"
dirs = "1.0"
tempfile = "3"
